Repository BHoM/Lusas_Toolkit, pull requests merged in 2020-09, with the labels that each got.

#281 Updated ReadMe to include Version 19
  README.md
Labels: severity:critical, size:XS, type:documentation

#282 Changed default element type to Thick Beam (BMI21)
  Lusas_Adapter/CRUD/Create/Properties/LineMesh.cs
Labels: severity:medium, size:XS, type:bug

#284 Fixing bug with incorrect Isection, Angle and Channel being pushed
  Lusas_Adapter/CRUD/Create/Properties/GeometricLine.cs
Labels: severity:medium, size:S, type:bug
