Repository BHoM/Lusas_Toolkit, pull requests merged in 2024-01, with the labels that each got.

#391 Update readme link
  README.md
Labels: type:documentation

#394 Align with removal of deprecated methods
  Lusas_Adapter/Convert/ToBHoM/Elements/ToPanel.cs
Labels: type:compliance

#395 Remove RuntimeReduction methods and any reference to them
  Lusas_Adapter/CRUD/Create/Create.cs
  Lusas_Adapter/Lusas_Adapter.csproj
  Lusas_Adapter/Private Helpers/RuntimeReduction.cs
Labels: type:bug
